/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __LAAS_SHERLOCK_ALL_TYPES_H__
#define __LAAS_SHERLOCK_ALL_TYPES_H__

#include <laas_sherlock/types/type_definitions.h>


#endif /* __LAAS_SHERLOCK_ALL_TYPES_H__ */
