/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __LAAS_SHERLOCK_TYPE_DEFINITIONS_H__
#define __LAAS_SHERLOCK_TYPE_DEFINITIONS_H__


#endif /* __LAAS_SHERLOCK_TYPE_DEFINITIONS_H__ */
